function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Jul-2017 19:05:17

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.13 0.11 0.775 0.815]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','G(PO)MDP    \delta=0.95','Color',[0 0 1]);
set(plot1(2),'DisplayName','G(PO)MDP    \delta=0.75','Color',[1 0 0]);
set(plot1(3),'DisplayName','G(PO)MDP    \delta = 0.5','Color',[0 1 0]);
set(plot1(4),'DisplayName','G(PO)MDP    \delta = 0.25','Color',[0 1 1]);
set(plot1(5),'DisplayName','G(PO)MDP    \delta = 0.05','Color',[1 1 0]);
set(plot1(6),'DisplayName','REINFORCE    \delta = 0.95','LineStyle','--',...
    'Color',[0 0 1]);
set(plot1(7),'DisplayName','REINFORCE    \delta = 0.75','LineStyle','--',...
    'Color',[1 0 0]);
set(plot1(8),'DisplayName','REINFORCE    \delta = 0.5','LineStyle','--',...
    'Color',[0 1 0]);

% Create xlabel
xlabel('Trajectory','FontSize',15.4);

% Create ylabel
ylabel('Expected performance','FontSize',15.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 30000000]);
% Set the remaining axes properties
set(axes1,'FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.706738544474394 0.129191321499014 0.191194968553468 0.369329388560158],...
    'FontSize',14);

set(figure,'Units','Inches');

pos = get(figure,'Position');

set(figure,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])

print(figure,'test.pdf','-dpdf','-r0')
